PODS-9114: Fix for memberDetails JsonValidationError.
hmrc/pension-scheme-accounting-for-tax-frontend pull request #678
Opened 2024-07-10 17:01 UTC by rambabu-posa

2024-07-11 08:22 UTC, dynamicwave4 submitted a review, later dismissed

2024-07-18 09:46 UTC, LauraToddCodes requested changes
Looks good, just some commented code that needs removing

2024-07-18 09:46 UTC, LauraToddCodes commented on app/models/ChargeType.scala
> +//  val chargeTypeValues: Seq[String] =
Can we remove this if not needed?

2024-07-18 10:35 UTC, LauraToddCodes approved these changes

2024-07-18 10:35 UTC, merged